vars:
  api-version: /api/v1
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: fluffybestapp
    password: fluffybestapp
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        hbm2ddl:
          charset_name: UTF-8
  flyway:
    enabled: false
logging:
  level:
    ### log just the SQL
    org.hibernate.SQL: DEBUG
    ### log JDBC bind parameters
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql: TRACE