vars:
  api:
    version-url: /api/v1
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: fluffybestapp
    password: fluffybestapp
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        default_schema: fluffybestapp
        hbm2ddl:
          charset_name: UTF-8
  flyway:
    enabled: true
    schemas: fluffybestapp
    default-schema: fluffybestapp
    placeholders:
      mySchema: fluffybestapp
logging:
  charset:
    console: UTF-8
  level:
    ### log just the SQL
    org.hibernate.SQL: DEBUG
    ### log JDBC bind parameters
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql: TRACE